# Generated by Django 3.0.5 on 2020-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='bio',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('u', 'user'), ('a', 'admin'), ('m', 'moderator')], default='u', max_length=25),
        ),
    ]
